name: EcoCrates
version: ${projectVersion}
main: com.willfp.ecocrates.EcoCratesPlugin
api-version: 1.17
authors: [ Auxilor ]
website: willfp.com
folia-supported: true
depend:
  - eco
softdepend:
  - CrateReloaded
  - ExcellentCrates
  - CrazyCrates
  - SpecializedCrates

commands:
  ecocrates:
    aliases:
      - crates
      - crate
      - key
      - keys
    description: Base plugin command
    permission: ecocrates.command.ecocrates

permissions:
  ecocrates.*:
    description: All ecocrates permissions
    default: op
    children:
      ecocrates.command.reload: true
      ecocrates.command.ecocrates: true
      ecocrates.command.give: true
      ecocrates.command.take: true
      ecocrates.command.open: true
      ecocrates.command.open.others: true
      ecocrates.command.preview: true
      ecocrates.command.keys: true
      ecocrates.command.set: true
      ecocrates.command.forceopen: true
      ecocrates.command.forceopen.others: true
      ecocrates.command.resetwins: true
      ecocrates.command.convert: true
      ecocrates.command.giveall: true
      ecocrates.command.giveoffline: true
      ecocrates.rewards.*: true
      ecocrates.break: true
      ecocrates.open.*: true
      ecocrates.reroll.*: true

  ecocrates.command.ecocrates:
    description: Allows the use of /ecocrates (base command)
    default: true
  ecocrates.command.reload:
    description: Allows reloading the config
    default: op
  ecocrates.command.give:
    description: Allows giving players keys
    default: op
  ecocrates.command.giveall:
    description: Allows giving all online players keys
    default: op
  ecocrates.command.giveoffline:
    description: Allows giving all online and offline players keys
    default: op
  ecocrates.command.take:
    description: Allows taking players keys
    default: op
  ecocrates.command.open:
    description: Allows opening crates with /ecocrates open
    default: true
  ecocrates.command.open.others:
    description: Allows opening crates for other people with /ecocrates open
    default: op
  ecocrates.command.forceopen:
    description: Allows opening crates with /ecocrates forceopen
    default: op
  ecocrates.command.forceopen.others:
    description: Allows opening crates for other people with /ecocrates forceopen
    default: op
  ecocrates.command.preview:
    description: Allows previewing crates with /ecocrates preview
    default: true
  ecocrates.command.keys:
    description: Allows viewing owned keys with /ecocrates keys
    default: true
  ecocrates.command.set:
    description: Allows marking a block as a crate
    default: op
  ecocrates.command.resetwins:
    description: Allows resetting a players tracked reward wins
    default: op
  ecocrates.command.convert:
    description: Allows converting crates over from other plugins
    default: op
  ecocrates.break:
    description: Allows breaking crate blocks
    default: op
  ecocrates.open.*:
    description: Allows opening all crates
    default: true
  ecocrates.reroll.*:
    description: Allows rerolling all crates
    default: true
  ecocrates.rewards.*:
    description: Allows getting all rewards
    default: true
